name: carrito_de_compras
description: A new Flutter application.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  pedantic: ^1.9.0
  cloud_firestore: ^0.13.7
  flutter_bloc: ^6.1.3
  provider: ^4.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - assets/img/barcode.png

  
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/font/Montserrat-Regular.ttf
          style: italic


  uses-material-design: true

